name: Docker Lint and Build
on: [push]

jobs:
  lint:
    ...
  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: lint # wait for lint to complete successfully
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      # action to login to GitHub container registry
      - name: Login to GitHub container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io # address to GitHub container registry
          username: ${{ github.actor }} # the user triggering the workflow
          password: ${{ secrets.GHCR_PUSH_TOKEN }} # The personal access token we have created earlier
      # action to build and push the image to GitHub container registry
      - name: Build and push image to GitHub container registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/greeter:latest
